server:
  port: 8089
spring:
  rabbitmq:
    host: 121.36.162.37
    port: 5672
    username: root
    password: xy@#782ABC*
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.225.14:3306/yztech?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    #\u8FDE\u63A5\u6C60\u7684\u8BBE\u7F6E
    druid:
      #\u521D\u59CB\u5316\u65F6\u5EFA\u7ACB\u7269\u7406\u8FDE\u63A5\u7684\u4E2A\u6570
      initial-size: 5
      #\u6700\u5C0F\u8FDE\u63A5\u6570\u91CF
      min-idle: 5
      #\u6700\u5927\u8FDE\u63A5\u6570\u91CF maxIdle\u5DF2\u7ECF\u4E0D\u518D\u4F7F\u7528
      max-active: 1000
      #\u83B7\u53D6\u8FDE\u63A5\u65F6\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u5355\u4F4D\u6BEB\u79D2
      max-wait: 60000
      #\u7533\u8BF7\u8FDE\u63A5\u7684\u65F6\u5019\u68C0\u6D4B\uFF0C\u5982\u679C\u7A7A\u95F2\u65F6\u95F4\u5927\u4E8EtimeBetweenEvictionRunsMillis\uFF0C\u6267\u884CvalidationQuery\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u3002
      test-while-idle: true
      #\u65E2\u4F5C\u4E3A\u68C0\u6D4B\u7684\u95F4\u9694\u65F6\u95F4\u53C8\u4F5C\u4E3AtestWhileIdel\u6267\u884C\u7684\u4F9D\u636E
      time-between-eviction-runs-millis: 60000
      #\u9500\u6BC1\u7EBF\u7A0B\u65F6\u68C0\u6D4B\u5F53\u524D\u8FDE\u63A5\u7684\u6700\u540E\u6D3B\u52A8\u65F6\u95F4\u548C\u5F53\u524D\u65F6\u95F4\u5DEE\u5927\u4E8E\u8BE5\u503C\u65F6\uFF0C\u5173\u95ED\u5F53\u524D\u8FDE\u63A5
      min-evictable-idle-time-millis: 30000
      #\u7528\u6765\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684sql \u5FC5\u987B\u662F\u4E00\u4E2A\u67E5\u8BE2\u8BED\u53E5
      #mysql\u4E2D\u4E3A select 'x'
      #oracle\u4E2D\u4E3A select 1 from dual
      validation-query: select 'x'
      #\u7533\u8BF7\u8FDE\u63A5\u65F6\u4F1A\u6267\u884CvalidationQuery\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548,\u5F00\u542F\u4F1A\u964D\u4F4E\u6027\u80FD,\u9ED8\u8BA4\u4E3Atrue
      test-on-borrow: false
      #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u4F1A\u6267\u884CvalidationQuery\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548,\u5F00\u542F\u4F1A\u964D\u4F4E\u6027\u80FD,\u9ED8\u8BA4\u4E3Atrue
      test-on-return: false
      #\u5F53\u6570\u636E\u5E93\u629B\u51FA\u4E0D\u53EF\u6062\u590D\u7684\u5F02\u5E38\u65F6,\u629B\u5F03\u8BE5\u8FDE\u63A5
      #spring.datasource.druid.exception-sorter=true
      #\u662F\u5426\u7F13\u5B58preparedStatement,mysql5.5+\u5EFA\u8BAE\u5F00\u542F
      #spring.datasource.druid.pool-prepared-statements=true
      #\u5F53\u503C\u5927\u4E8E0\u65F6poolPreparedStatements\u4F1A\u81EA\u52A8\u4FEE\u6539\u4E3Atrue
      max-pool-prepared-statement-per-connection-size: 20
      #\u914D\u7F6E\u6269\u5C55\u63D2\u4EF6
      filters: stat,wall,slf4j,config
      #\u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
      #connection-properties:  config.decrypt=true;
      #\u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
      use-global-data-source-stat: true
      #\u8BBE\u7F6E\u8BBF\u95EEdruid\u76D1\u63A7\u9875\u7684\u8D26\u53F7\u548C\u5BC6\u7801,\u9ED8\u8BA4\u6CA1\u6709
      #stat-view-servlet.login-username=admin
      #stat-view-servlet.login-password=admin
  #\u914D\u7F6Eredis
  redis:
    host: 1.117.225.14
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        # 这里在IDEA中显示红色错误，不用管，因为org.springframework.boot.autoconfigure.data.redis.RedisProperties.Pool.setMaxWait(Duration maxWait)
        # 方法参数是Duration，IDEA无法识别，但是会自动注入成功
        max-wait: 2000 # 当连接池耗尽时， 抛出异常之前，连接分配被阻塞的时间，也就是连接池满后最长等待时间，负值表示无限期等待
    # jackson\u65F6\u95F4\u683C\u5F0F\u5316
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Mybatis-Plus \u914D\u7F6E
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  typeAliasesPackage: com.yzchn.admin.dao.mapper
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #\u914D\u7F6E\u7684\u7F13\u5B58\u7684\u5168\u5C40\u5F00\u5173
    lazyLoadingEnabled: true #\u5EF6\u65F6\u52A0\u8F7D\u7684\u5F00\u5173
    multipleResultSetsEnabled: true #\u5F00\u542F\u7684\u8BDD\uFF0C\u5EF6\u65F6\u52A0\u8F7D\u4E00\u4E2A\u5C5E\u6027\u65F6\u4F1A\u52A0\u8F7D\u8BE5\u5BF9\u8C61\u5168\u90E8\u5C5E\u6027\uFF0C\u5426\u5219\u6309\u9700\u52A0\u8F7D\u5C5E\u6027
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u6253\u5370sql\u8BED\u53E5,\u8C03\u8BD5\u7528