#appname=yz-auth
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
#spring.http.encoding.force=true
#logging.config=classpath:logback-spring.xml
#spring.profiles.active=test
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: cloud-platform-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
version: 1.0.1
